Now warns about the STF walltime
UW-HPC/Hyak-Gaussian pull request #6
Opened 2020-01-15 00:41 UTC by rbeck4

Added in functionality to check on the run time as well as adjust core cound and memory amount when assigned node(s).

2020-01-22 18:30 UTC, awild82 requested changes

2020-01-22 18:30 UTC, awild82 commented on gaussian-sub.py
> +            allocation = 'hyak-stf'
We were specifically asked by UW-IT not to have a default group, so remove this (see #3 )

2020-01-22 22:47 UTC, rbeck4 commented
Done

2020-02-01 04:09 UTC, awild82 commented
Looks good to me. Merging.

2020-02-01 04:09 UTC, merged